galaxy_info:
  author: Shailesh Thakur
  description: DevOps Engineer
  company: osgroup-techies
  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2


  galaxy_tags: []

dependencies: []

